Impleted testings
thedekerone/Enumerable-Methods pull request #6
Opened 2020-05-07 20:04 UTC by thedekerone

In this PR we implemented test cases for every Enumerable method.

2020-05-08 18:32 UTC, shshamim63 requested changes
## Status :traffic_light: Changes Required :tractor: 
___
Hi @thedekerone and @shubhsk88 
Awesome job. Tests look well- organized, you have used let to define variables. Also added test for methods which should raise an error. Amazing :clap: . But just found some simple corner cases, which are holding me back to approve it now. And it is really easy to cover them. Let's get to them.
___
### :spades: Mandatory Changes :spades: 
___
1. I can not see any info related to the test in your Readme. Can you add some instruction like which testing tools you have used (obviously Rspec). And how to execute them.
2. I think some negative scenarios are needed to the following methods
- my_all?
- my_any?
- my_none?
the negative cases like when it should return false if you have a case where it returns true. Add them for the following cases
- when class is given
- when a regex is given
___
### :clubs: Optional Changes :clubs: 
___
- You can update some of your tests to compare them with the actual methods. I have added a sample. Well, that will help you to get an overview.
- I also added some suggestions with your test block messages. I will suggest you update some of your messages so that it can deliver the actual test criteria.
___
##### Please fix the issues mentioned above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-08 18:32 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +require './my_each.rb'
[Optional]
when you are requiring a file it is best practice to use, `require_relative` so the line should look like,
```ruby
require_relative '../my_each.rb'
```

2020-05-08 18:32 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +      end
[Optional]
must execute what? I would say, 'calls the given block for each element'
And you can make this test more solid, by comparing it with the actual `each` method. I just modified your current test into this format,
```ruby
it 'calls the block for each element' do
  test_array = []
  block = proc { |x| test_array.push(x + 2) }
  array.each(&block)
  actual_output = test_array.dup
  test_array = []
  array.my_each(&block)
  expect(test_array).to eql(actual_output)
end
```

2020-05-08 18:32 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +  let(:array) { Array.new([1, 2, 3]) }
[Optional]
`Array.new` actually no needed. just [1, 2, 3] will do it. Now seems to me like you are trying to create a copy of an array. That is not needed.

2020-05-08 18:32 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +    context 'When the neither the block or parameter is given' do
did you mean, When neither the block or parameter is given?

2020-05-08 18:32 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +      it 'any element matches the condition in block' do
[Optional]
You can organize the message like this way
`returns true if the block returns true for any element`

2020-05-08 18:32 UTC, shshamim63 commented on spec/enumerable_spec.rb
> +      it 'none of the elements matches the condition in block' do
[Optional]
same as the above :point_up: .

2020-05-09 17:04 UTC, mosesogwo approved these changes
**Congratulations, your project is approved:+1:**

**Good luck in your next project :stars:**

### Status: Approved:heavy_check_mark:

2020-05-09 17:11 UTC, merged